# Generated by Django 5.1.3 on 2024-12-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_blog_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
    ]
