# Generated by Django 5.1.3 on 2024-12-06 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_feedback_testimonial_testimonial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='client_name',
            new_name='name',
        ),
    ]
