# Generated by Django 5.1.3 on 2024-12-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_client_name_testimonial_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='testimonial',
            new_name='content',
        ),
    ]
