# Generated by Django 5.1.3 on 2024-12-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_testimonial_testimonial_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
