# Generated by Django 5.1.3 on 2024-12-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_carouselitem_delete_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('phone_number', models.CharField(max_length=15)),
                ('hours', models.CharField(max_length=50)),
                ('services', models.JSONField()),
            ],
        ),
    ]
