# Generated by Django 5.1.3 on 2024-12-12 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_footer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='Header',
        ),
    ]
